adding 3 retries

diff --git a/.github/workflows/on-pullrequest.yml b/.github/workflows/on-pullrequest.yml
--- a/.github/workflows/on-pullrequest.yml
+++ b/.github/workflows/on-pullrequest.yml
@@ -138,7 +138,7 @@ jobs:
         shell: pwsh
     services:
       postgres:
-        image: postgres:14
+        image: postgres:14.12
         options: >-
           --health-cmd="pg_isready"
           --health-interval=10s
@@ -157,7 +157,23 @@ jobs:
 
       - name: Run Integration Tests
         if: success()
-        run: ./build.ps1 IntegrationTest -Configuration Debug
+        run: |
+          retries=3
+          until_failure=0
+          while [ $retries -gt 0 ]; do
+            ./build.ps1 IntegrationTest -Configuration Debug
+            exit_code=$?
+            if [ $exit_code -eq 0 ]; then
+              break
+            elif [ $exit_code -eq 1 ] && [ $until_failure -lt 3 ]; then
+              until_failure=$((until_failure + 1))
+              echo "Retrying (attempt $until_failure of 3)..."
+            else
+              echo "Integration tests failed with exit code $exit_code, no retries left."
+              exit 1
+            fi
+            retries=$((retries - 1))
+          done
 
   run-e2e-tests:
     name: Run E2E Tests
